name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      IMG_URL:    
        description: 'IMG_URL'
        required: true
        default: ''

jobs:
  build:
    timeout-minutes: 30 #超时设置
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
   
    
    steps:
    - name: Check Out
      uses: actions/checkout@v4
      
    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install software-properties-common # 确保add-apt-repository可用
        sudo add-apt-repository universe -y # 添加universe仓库
        sudo apt update
        # 安装Python3和相关工具
        sudo apt -y install python3 python3-pip python3-dev cpio wget aria2
        # 创建python指向python3的符号链接
        sudo ln -sf /usr/bin/python3 /usr/bin/python
        # 验证安装
        python --version
        pip3 --version
        mkdir dt
      
    - name: Download boot or recovery img
      run: |
        aria2c "${{ github.event.inputs.IMG_URL }}"
        ls
      
    - name: Start build
      run: |
        python3 -m twrpdtgen -o dt/ *.img
    - name: ZIP device tree
      run: |
        zip -r DeviceTree.zip ./dt
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./DeviceTree.zip
        name: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: build-${{ github.run_id }}
        body: DeviceTree for twrp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
